# Site settings
title: Prajyot Rajendra Mane
email: prajyotmane464@gmail.com
description: Technology enthusiast | Programmer | Application developer
baseurl: "/highlights-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: https://facebook.com/prajyotmane
github_url: https://github.com/Prajyotmane464
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/prajyotmane
linkedin_url: https://www.linkedin.com/in/prajyotmane
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
